# Generated by Django 5.1.6 on 2025-02-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('MATH', 'MathGame'), ('ANAGRAM', 'AnagramGame')], default='MATH'),
        ),
    ]
