# Generated by Django 5.1.6 on 2025-02-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
